import type { NextPage } from "next";
import Head from "next/head";
import { useDispatch, useSelector } from "react-redux";
import Layout from "../components/layout";
import { selectAuthState, setAuthState } from "../slices/authSlice";
import {
  decrement,
  increment,
  incrementAsyncByAmount,
  selectCountState,
} from "../slices/couterSlice";

const Home: NextPage = () => {
  const dispatch = useDispatch();
  const authState = useSelector(selectAuthState);
  const counterValue = useSelector(selectCountState);

  return (
    <div>
      <Head>
        <title>Events - nadamas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icons.icon.ico" />
      </Head>
      <Layout>
        <div className="text-center h-60 flex w-full flex-col justify-center items-center">
          <h1 className="text-4xl">This is your new favorite sport events page</h1>
          <p className="text-xl my-4">wait for it</p>
        </div>
      </Layout>
    </div>
  );
};

export default Home;
