import type { NextPage } from 'next';
import Head from 'next/head';
import Layout from '../components/layout';
import Hero from '@comps/hero';
import EventsList from '@comps/events/eventsList';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>events - nadamas</title>
        <meta name="description" content="Generated by create next app" />

        {/* ---- icons ----- */}

        <link rel="icon" href="/icons.icon.ico" />
        <link rel="manifest" href="/manifest.json" />
        <link
          href="/icons.icon.png"
          rel="icon"
          type="image/png"
          sizes="16x16"
        />
        <link
          href="/icons.icon.png"
          rel="icon"
          type="image/png"
          sizes="32x32"
        />
        <link rel="apple-touch-icon" href="/icons.icon.png"></link>

        {/* ---- meta tags ----- */}

        <meta charSet="utf-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta
          name="viewport"
          content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no"
        />

        {/* ---- pwa default theme ----- */}

        <meta name="theme-color" content="#317EFB" />
      </Head>
      <Layout>
        <Hero />
        <EventsList />
      </Layout>
    </div>
  );
};

export default Home;
